### PR TITLE
Add initial implementation

### PR DESCRIPTION
**Pull request by SemenchenkoVitaliy**

### CODE REVIEW

**Comment by SemenchenkoVitaliy** [comment]
ping @tshemsedinov.

**Comment by DzyubSpirit** [comment]
I would suggest you divide this PR into multiple smaller PRs. That will make it easier for reviewing and you'll get a review faster (because big PRs require more time investment, I would say O(n^2) time | n > 100, where n - a number of lines)

**Comment by SemenchenkoVitaliy** [comment]
@DzyubSpirit This code was already reviewed in https://github.com/metarhia/metaschema/pull/107. We are just moving doc generation into a separate repository since the main purpose of [metaschema](https://github.com/metarhia/metaschema) changed.

**Comment by belochub** [comment]
Landed in https://github.com/metarhia/metadoc/commit/660113503501fa1176509e9466193d619448b5c7.

**Pull request closed without merging**
