### PR TITLE
Release version 0.4.0

### PR DESCRIPTION
**Pull request by lundibundi**

### CODE REVIEW

**Comment by lundibundi** [comment]
@SemenchenkoVitaliy what dependencies are you referring to? They all seem up to date to me.

**Comment by SemenchenkoVitaliy** [comment]
@lundibundi [eslint-config-prettier@4.1.0](https://www.npmjs.com/package/eslint-config-prettier).

**Comment by SemenchenkoVitaliy** [comment]
To be landed after https://github.com/metarhia/metadoc/pull/29.

**Comment by lundibundi** [comment]
Landed in https://github.com/metarhia/metadoc/commit/bf0fbc0ffaabb5ad689f2966d8621c4106d3ec2e.

**Pull request closed without merging**
